apiVersion: v1
kind: Deployment # deployment is a template for creating pods
metadata:
  name: my-app
  labels: 
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabel:
      app: my-app
  template:
    metadata:
      labels:
        apps: my-app
    spec:
      containers:
        - name: my-app
          image: my-image
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080